#!/bin/bash

# Compile selected source files
compile () {
   objlist=()
   for file in "$@"; do
      srcfile=$SRCDIR/$file
      bldfile=$OBJDIR/$file
      objfile=$OBJDIR/${file%.*}.o
      objlist+=($objfile)
      if ! test -e "$objfile" || ! test -e "$bldfile" || ! diff -q "$srcfile" "$bldfile" > /dev/null; then
         rm -f "$objfile"
         cp -p "$srcfile" "$bldfile"
         echo Compiling "$file"
         $FORTRAN -c "$srcfile" -o "$objfile" -I "$OBJDIR" -J "$OBJDIR" || exit
      fi
   done
}

build () {
   case "$1" in
     single ) prec_options='' ;;
     double ) prec_options='-fdefault-real-8' ;;
     * ) echo Invalid precision option: $1; exit ;;
   esac
   case "$2" in
     standard ) bld_options='-O3' ;;
     debug ) bld_options='-g -fbounds-check -fbacktrace -ffpe-trap=zero,invalid,overflow -O0 -Wall' ;;
     fast ) bld_options='-O3 -ffast-math' ;;
     * ) echo Invalid optimization option: $2; exit ;;
   esac
   FORTRAN="gfortran $bld_options $prec_options -L/usr/lib64/atlas -llapack"
   OBJDIR=$BLDDIR/$1/$2
   srclist=()
   if [[ -d $OBJDIR ]]; then
      if [[ $RECOMPILE != true ]]; then
         for f in "$OBJDIR"/*; do 
            rm "$f"
         done
      fi
   else
      mkdir -p "$OBJDIR"
   fi
   while IFS= read -r line; do
      srclist+=("$line")
   done < <(grep -v '^#' "$SRCLIST")
   compile "${srclist[@]}"
   echo Linking $BINARY
   $FORTRAN "${objlist[@]}" -o "$BINDIR/$BINARY"
   echo
} 

shopt -s nullglob

SRCDIR=./source
SRCLIST=./srclist
BLDDIR=./build
BINDIR=./bin
BINARY=ralign

if [[ -d $BINDIR ]]; then
   for file in "$BINDIR"/*; do 
      rm "$file"
   done
else
   mkdir "$BINDIR"
fi

TEMP=$(getopt -a -o '' -l single,double,fast,debug -- "$@")
if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
eval set -- "$TEMP"

precision=double
buildtype=standard
while true; do
   case "$1" in
      --fast ) buildtype=fast; shift ;;
      --debug ) buildtype=debug; shift ;;
      --single ) precision=single; shift ;;
      --double ) precision=double; shift ;;
      -- ) shift; break ;;
   esac
done

build "$precision" "$buildtype"
