[build-system]
requires = [
  "scikit-build-core>=0.10",
  "cython>=3.0",
  "numpy>=1.19.2",
]
build-backend = "scikit_build_core.build"

[project]
name = "molalignlib"
version = "0.1.0"
description = "Python bindings for MolAlignLib via Cython"
requires-python = ">=3.8"
dependencies = [
  "numpy",
  "chemfiles",
]

[tool.setuptools.packages.find]
where = ["python"]

[tool.scikit-build]
wheel.packages = ["python/molalignlib"]
