! MolAlignLib
! Copyright (C) 2022 José M. Vásquez

! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.

! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.

! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https://www.gnu.org/licenses/>.

module file_write
use parameters
use options
use chemistry
use molecule
use permutation
implicit none

contains

subroutine open2write(filepath, unit)
   character(*), intent(in) :: filepath
   integer, intent(out) :: unit
   integer :: stat

   open(newunit=unit, file=filepath, action='write', status='replace', iostat=stat)
   if (stat /= 0) then
      write (stderr, '(A,1X,A,1X,A)') 'Error opening', filepath, 'for writing'
      stop
   end if
end subroutine

subroutine writemol(unit, extout, title, atoms, atomperm_arg)
   integer, intent(in) :: unit
   character(*), intent(in) :: extout
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   integer, dimension(:), intent(in), optional :: atomperm_arg
   ! Local varibles
   integer, dimension(:), allocatable :: atomperm

   if (present(atomperm_arg)) then
      atomperm = atomperm_arg
   else
      atomperm = identity_permutation(size(atoms))
   end if

   select case (extout)
   case ('xyz')
      call writemol_xyz(unit, title, atoms, atomperm)
   case ('mol2')
      call writemol_mol2(unit, title, atoms, atomperm)
   case ('sdf')
      call writemol_sdf(unit, title, atoms, atomperm)
   case default
      write (stderr, '(A,1X,A)') 'Invalid format:', extout
      stop
   end select

   flush(stderr)
end subroutine

subroutine writemol_xyz(unit, title, atoms, atomperm)
   integer, intent(in) :: unit
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   integer, dimension(:), intent(in) :: atomperm
   ! Local varibles
   type(atom_t) :: iatom
   integer :: i

   write (unit, '(I0)') size(atoms)
   write (unit, '(A)') title

   do i = 1, size(atomperm)
      iatom = atoms(atomperm(i))
      write (unit, '(A,3(2X,F12.6))') element_symbols(iatom%elnum), iatom%coords
   end do
end subroutine

subroutine writemol_mol2(unit, title, atoms, atomperm)
! Write SYBYL MOL2 files
   integer, intent(in) :: unit
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   integer, dimension(:), intent(in) :: atomperm
   ! Local variables
   type(atom_t) :: iatom
   type(bond_t), allocatable :: bonds(:)
   integer, allocatable :: invperm(:)
   integer :: num_atoms, num_bonds, i

   bonds = get_bonds(atoms)
   invperm = inverse_permutation(atomperm)

   num_atoms = size(atoms)
   num_bonds = size(bonds)

   write (unit, '(A)') '@<TRIPOS>MOLECULE'
   if (title /= '') then
      write (unit, '(A)') title
   else
      write (unit, '(A)') 'Untitled'
   end if
   write (unit, '(5(I4,1X))') num_atoms, num_bonds, 0, 0, 0
   write (unit, '(A)') 'SMALL'
   write (unit, '(A)') 'NO_CHARGES'

   write (unit, '(A)') '@<TRIPOS>ATOM'
   do i = 1, num_atoms
      iatom = atoms(atomperm(i))
      write (unit, '(I4,2X,A2,3(1X,F12.6),2X,A4,1X,I2,1X,A4,1X,F7.3)') &
         i, element_symbols(iatom%elnum), iatom%coords, 'Any', 1, 'MOL1', 0.
   end do

   write (unit, '(A)') '@<TRIPOS>BOND'
   do i = 1, num_bonds
      write (unit, '(I4,1X,2(1X,I4),1X,A2)') i, invperm(bonds(i)%idx1), invperm(bonds(i)%idx2), 'un'
   end do
end subroutine

subroutine writemol_sdf(unit, title, atoms, atomperm)
! Write SDF (Structure Data Format) files
   integer, intent(in) :: unit
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   integer, dimension(:), intent(in) :: atomperm
   ! Local variables
   type(atom_t) :: iatom
   type(bond_t), dimension(:), allocatable :: bonds
   integer, dimension(:), allocatable :: invperm
   integer :: i, num_atoms, num_bonds

   bonds = get_bonds(atoms)
   invperm = inverse_permutation(atomperm)

   num_atoms = size(atoms)
   num_bonds = size(bonds)

   ! Header block (3 lines)
   if (title /= '') then
      write (unit, '(A)') title
   else
      write (unit, '(A)') 'Untitled'
   end if
   write (unit, '(A)') '  Generated by MolAlignLib'
   write (unit, '(A)') ''

   ! Counts line: aaabbblllfffcccsssxxxrrrpppiiimmmvvvvvv
   ! Format: I3,I3,I3,I3,I3,I3,I3,I3,I3,I3,I3,V3000
   write (unit, '(I3,I3,I3,I3,I3,I3,I3,I3,I3,I3,I3,A6)') &
      num_atoms, num_bonds, 0, 0, 0, 0, 0, 0, 0, 0, 999, ' V2000'

   ! Atom block
   ! Format: xxxxx.xxxxyyyyy.yyyyzzzzz.zzzz aaaddcccssshhhbbbvvvHHHrrriiimmmnnneee
   do i = 1, num_atoms
      iatom = atoms(atomperm(i))
      write (unit, '(3F10.4,1X,A3,I2,3I3,3I3,2I3,2I3,2I3)') &
         iatom%coords, element_symbols(iatom%elnum), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
   end do

   ! Bond block
   ! Format: 111222tttsssxxxrrrccc
   do i = 1, num_bonds
      ! Map original atom indices to permuted indices
      write (unit, '(I3,I3,I3,I3,I3,I3)') invperm(bonds(i)%idx1), invperm(bonds(i)%idx2), 1, 0, 0, 0
   end do

   ! Properties block (none for now)
   write (unit, '(A)') 'M  END'

   ! SDF record separator (for multiple molecules)
   write (unit, '(A)') '$$$$'
end subroutine

end module
