! MolAlignLib
! Copyright (C) 2025 José M. Vásquez

! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.

! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.

! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https://www.gnu.org/licenses/>.

module file_writing
use parameters
use permutation
use chemdata
use molecule
use flags

implicit none

private
public write_file

contains

subroutine write_file(unit, out_format, title, atoms, bonds, mapping1)
! Write the atoms in the order atoms(mapping1(i)), in the given format.
! Padding atoms (elnum = PADDING_ELNUM) are written as dummy atoms X.
   integer(ik), intent(in) :: unit
   character(*), intent(in) :: out_format
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   type(bond_t), dimension(:), intent(in) :: bonds
   integer(ik), dimension(:), intent(in) :: mapping1

   select case (out_format)
   case ('xyz')
      call write_file_xyz(unit, title, atoms, bonds, mapping1)
   case ('sdf')
      call write_file_sdf(unit, title, atoms, bonds, mapping1)
   case ('mol2')
      call write_file_mol2(unit, title, atoms, bonds, mapping1)
   case default
      write (stderr, '(A,A,A)') 'File format "', out_format, '" is not supported'
      stop
   end select
end subroutine

subroutine write_file_xyz(unit, title, atoms, bonds, mapping1)
   integer(ik), intent(in) :: unit
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   type(bond_t), dimension(:), intent(in) :: bonds
   integer(ik), dimension(:), intent(in) :: mapping1
   ! Local variables
   type(atom_t) :: iatom
   integer(ik) :: n_atoms, i

   n_atoms = size(atoms)

   write (unit, '(I0)') n_atoms
   write (unit, '(A)') title

   do i = 1, n_atoms
      iatom = atoms(mapping1(i))
      write (unit, '(A,3(2X,F12.6))') element_symbol(iatom%elnum), iatom%coords
   end do
end subroutine

subroutine write_file_sdf(unit, title, atoms, bonds, mapping1)
! Write SDF (Structure Data Format) files
   integer(ik), intent(in) :: unit
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   type(bond_t), dimension(:), intent(in) :: bonds
   integer(ik), dimension(:), intent(in) :: mapping1
   ! Local variables
   type(atom_t) :: iatom
   integer(ik), dimension(:), allocatable :: mapping2
   integer(ik) :: atomidx1, atomidx2, bondtype
   integer(ik) :: n_atoms, n_bonds, i

   mapping2 = inverse_permutation(mapping1)

   n_atoms = size(atoms)
   n_bonds = size(bonds)

   ! Header block (3 lines)
   if (title /= '') then
      write (unit, '(A)') title
   else
      write (unit, '(A)') 'Untitled'
   end if
   write (unit, '(A)') '  Generated by MolAlignLib'
   write (unit, '(A)') ''

   ! Counts line (V2000): aaabbblllfffcccsssxxxrrrpppiiimmmvvvvvv
   write (unit, '(I3,I3,I3,I3,I3,I3,I3,I3,I3,I3,I3,A6)') &
      n_atoms, n_bonds, 0, 0, 0, 0, 0, 0, 0, 0, 999, ' V2000'

   ! Atom block
   ! Format: xxxxx.xxxxyyyyy.yyyyzzzzz.zzzz aaaddcccssshhhbbbvvvHHHrrriiimmmnnneee
   do i = 1, n_atoms
      iatom = atoms(mapping1(i))
      write (unit, '(3F10.4,1X,A3,I2,11I3)') &
         iatom%coords, element_symbol(iatom%elnum), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
   end do

   ! Bond block
   ! Format: 111222tttsssxxxrrrccc
   do i = 1, size(bonds)
      atomidx1 = mapping2(bonds(i)%atomidx1)
      atomidx2 = mapping2(bonds(i)%atomidx2)
      bondtype = sdf_bondnumber(bonds(i)%bondtype)
      ! V2000 has no coordination (9) or hydrogen (10) bonds
      if (bondtype > 8) bondtype = 8
      write (unit, '(I3,I3,I3,I3,I3,I3,I3)') atomidx1, atomidx2, bondtype, 0, 0, 0, 0
   end do

   ! End of the (empty) properties block
   write (unit, '(A)') 'M  END'

   ! SDF record separator
   write (unit, '(A)') '$$$$'
end subroutine

subroutine write_file_mol2(unit, title, atoms, bonds, mapping1)
! Write SYBYL MOL2 files
   integer(ik), intent(in) :: unit
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   type(bond_t), dimension(:), intent(in) :: bonds
   integer(ik), dimension(:), intent(in) :: mapping1
   ! Local variables
   type(atom_t) :: iatom
   integer(ik), dimension(:), allocatable :: mapping2
   character(4) :: bondtype, atomtype
   integer(ik) :: atomidx1, atomidx2
   integer(ik) :: n_atoms, n_bonds, bond_id, i

   mapping2 = inverse_permutation(mapping1)

   n_atoms = size(atoms)
   n_bonds = size(bonds)

   write (unit, '(A)') '@<TRIPOS>MOLECULE'
   if (title /= '') then
      write (unit, '(A)') title
   else
      write (unit, '(A)') 'Untitled'
   end if
   write (unit, '(5(I4,1X))') n_atoms, n_bonds, 0, 0, 0
   write (unit, '(A)') 'SMALL'
   write (unit, '(A)') 'NO_CHARGES'

   write (unit, '(A)') '@<TRIPOS>ATOM'
   do i = 1, n_atoms
      iatom = atoms(mapping1(i))
      select case (iatom%elnum)
      case (PADDING_ELNUM)
         atomtype = 'Du'
      case (1)
         atomtype = 'H'
      case default
         atomtype = 'Hev'
      end select
      write (unit, '(I4,2X,A2,3(1X,F12.6),2X,A4,1X,I2,1X,A4,1X,F7.3)') &
         i, element_symbol(iatom%elnum), iatom%coords, atomtype, 1, 'MOL1', 0.
   end do

   write (unit, '(A)') '@<TRIPOS>BOND'
   bond_id = 0
   do i = 1, size(bonds)
      bond_id = bond_id + 1
      atomidx1 = mapping2(bonds(i)%atomidx1)
      atomidx2 = mapping2(bonds(i)%atomidx2)
      bondtype = mol2_typestr(bonds(i)%bondtype)
      write (unit, '(I4,1X,2(1X,I4),1X,A2)') bond_id, atomidx1, atomidx2, bondtype
   end do
end subroutine

end module
