! MolAlignLib
! Copyright (C) 2025 José M. Vásquez

! This program is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.

! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.

! You should have received a copy of the GNU General Public License
! along with this program.  If not, see <https://www.gnu.org/licenses/>.

module file_writing
use parameters
use permutation
use chemdata
use molecule
use flags

implicit none

private
public write_file

contains

subroutine write_file(unit, out_format, title, atoms, bonds, atomperm1)
   integer(ik), intent(in) :: unit
   character(*), intent(in) :: out_format
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   type(bond_t), dimension(:), intent(in) :: bonds
   integer(ik), dimension(:), intent(in) :: atomperm1

   select case (out_format)
   case ('xyz')
      call write_file_xyz(unit, title, atoms, bonds, atomperm1)
   case ('sdf')
      call write_file_sdf(unit, title, atoms, bonds, atomperm1)
   case ('mol2')
      call write_file_mol2(unit, title, atoms, bonds, atomperm1)
   case default
      write (stderr, '(A,A,A)') 'File format "', out_format, '" is not supported'
      stop
   end select
end subroutine

subroutine write_file_xyz(unit, title, atoms, bonds, atomperm1)
   integer(ik), intent(in) :: unit
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   type(bond_t), dimension(:), intent(in) :: bonds
   integer(ik), dimension(:), intent(in) :: atomperm1
   ! Local varibles
   type(atom_t) :: iatom
   integer(ik) :: n_atoms, i

   n_atoms = size(atoms)

   write (unit, '(I0)') n_atoms
   write (unit, '(A)') title

   do i = 1, n_atoms
      iatom = atoms(atomperm1(i))
      write (unit, '(A,3(2X,F12.6))') atomic_symbols(iatom%elnum), iatom%coords
   end do
end subroutine

subroutine write_file_sdf(unit, title, atoms, bonds, atomperm1)
! Write SDF (Structure Data Format) files
   integer(ik), intent(in) :: unit
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   type(bond_t), dimension(:), intent(in) :: bonds
   integer(ik), dimension(:), intent(in) :: atomperm1
   ! Local variables
   type(atom_t) :: iatom
   integer(ik), dimension(:), allocatable :: atomperm2
   integer(ik) :: atomidx1, atomidx2, bondtype
   integer(ik) :: n_atoms, n_bonds, i

   atomperm2 = inverse_permutation(atomperm1)

   n_atoms = size(atoms)
   n_bonds = size(bonds)

   ! Header block (3 lines)
   if (title /= '') then
      write (unit, '(A)') title
   else
      write (unit, '(A)') 'Untitled'
   end if
   write (unit, '(A)') '  Generated by MolAlignLib'
   write (unit, '(A)') ''

   ! Counts line: aaabbblllfffcccsssxxxrrrpppiiimmmvvvvvv
   ! Format: I3,I3,I3,I3,I3,I3,I3,I3,I3,I3,I3,V3000
   write (unit, '(I3,I3,I3,I3,I3,I3,I3,I3,I3,I3,I3,A6)') &
      n_atoms, n_bonds, 0, 0, 0, 0, 0, 0, 0, 0, 999, ' V2000'

   ! Atom block
   ! Format: xxxxx.xxxxyyyyy.yyyyzzzzz.zzzz aaaddcccssshhhbbbvvvHHHrrriiimmmnnneee
   do i = 1, n_atoms
      iatom = atoms(atomperm1(i))
      write (unit, '(3F10.4,1X,A3,I2,11I3)') &
         iatom%coords, atomic_symbols(iatom%elnum), 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
   end do

   ! Bond block
   ! Format: 111222tttsssxxxrrrccc
   do i = 1, n_bonds
      atomidx1 = atomperm2(bonds(i)%atomidx1)
      atomidx2 = atomperm2(bonds(i)%atomidx2)
      bondtype = atomperm2(bonds(i)%bondtype)
      write (unit, '(I3,I3,I3,I3,I3,I3,I3)') atomidx1, atomidx2, bondtype, 0, 0, 0, 0
   end do

   ! Properties block (none for now)
   write (unit, '(A)') 'M  END'

   ! SDF record separator (for multiple molecules)
   write (unit, '(A)') '$$$$'
end subroutine

subroutine write_file_mol2(unit, title, atoms, bonds, atomperm1)
! Write SYBYL MOL2 files
   integer(ik), intent(in) :: unit
   character(*), intent(in) :: title
   type(atom_t), dimension(:), intent(in) :: atoms
   type(bond_t), dimension(:), intent(in) :: bonds
   integer(ik), dimension(:), intent(in) :: atomperm1
   ! Local variables
   type(atom_t) :: iatom
   integer(ik), dimension(:), allocatable :: atomperm2
   character(4) :: bondtype, atomtype
   integer(ik) :: atomidx1, atomidx2
   integer(ik) :: n_atoms, n_bonds, i

   atomperm2 = inverse_permutation(atomperm1)

   n_atoms = size(atoms)
   n_bonds = size(bonds)

   write (unit, '(A)') '@<TRIPOS>MOLECULE'
   if (title /= '') then
      write (unit, '(A)') title
   else
      write (unit, '(A)') 'Untitled'
   end if
   write (unit, '(5(I4,1X))') n_atoms, n_bonds, 0, 0, 0
   write (unit, '(A)') 'SMALL'
   write (unit, '(A)') 'NO_CHARGES'

   write (unit, '(A)') '@<TRIPOS>ATOM'
   do i = 1, n_atoms
      iatom = atoms(atomperm1(i))
      if (iatom%elnum > 1) then
         atomtype = 'Hev'
      else
         atomtype = 'H'
      end if
      write (unit, '(I4,2X,A2,3(1X,F12.6),2X,A4,1X,I2,1X,A4,1X,F7.3)') &
         i, atomic_symbols(iatom%elnum), iatom%coords, atomtype, 1, 'MOL1', 0.
   end do

   write (unit, '(A)') '@<TRIPOS>BOND'
   do i = 1, n_bonds
      atomidx1 = atomperm2(bonds(i)%atomidx1)
      atomidx2 = atomperm2(bonds(i)%atomidx2)
      if (atomperm2(bonds(i)%bondtype) > 0) then
         bondtype = str(atomperm2(bonds(i)%bondtype))
      else
         bondtype = 'un'
      end if
      write (unit, '(I4,1X,2(1X,I4),1X,A2)') i, atomidx1, atomidx2, bondtype
   end do
end subroutine

end module
